version: '3'
services:
  cassandra-node1:
    image: cassandra:latest
    container_name: cassandra-node1
    ports:
      - "9042:9042"
    networks:
      - cassandra-net
    environment:
      - CASSANDRA_CLUSTER_NAME=MyCassandraCluster
      - CASSANDRA_LISTENER_IP=0.0.0.0
      - CASSANDRA_BROADCAST_ADDRESS=cassandra-node1
      - CASSANDRA_SEEDS=cassandra-node1

  cassandra-node2:
    image: cassandra:latest
    container_name: cassandra-node2
    ports:
      - "9043:9042"
    networks:
      - cassandra-net
    environment:
      - CASSANDRA_CLUSTER_NAME=MyCassandraCluster
      - CASSANDRA_LISTENER_IP=0.0.0.0
      - CASSANDRA_BROADCAST_ADDRESS=cassandra-node2
      - CASSANDRA_SEEDS=cassandra-node1

  cassandra-node3:
    image: cassandra:latest
    container_name: cassandra-node3
    ports:
      - "9044:9042"
    networks:
      - cassandra-net
    environment:
      - CASSANDRA_CLUSTER_NAME=MyCassandraCluster
      - CASSANDRA_LISTENER_IP=0.0.0.0
      - CASSANDRA_BROADCAST_ADDRESS=cassandra-node3
      - CASSANDRA_SEEDS=cassandra-node1

networks:
  cassandra-net:
    driver: bridge
